import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { MembersPanel } from './MembersPanel'
import { ApiError, apiFetch } from '../../lib/api'
import type { MembershipCapabilities, ProjectMemberRow } from '../../types/members'
vi.mock('../../lib/api', async () => ({ ...(await vi.importActual('../../lib/api')), apiFetch: vi.fn() }))
const caps: MembershipCapabilities = { can_invite_member:true, can_change_ordinary_role:true, can_transfer_sponsor:true, can_transfer_owner:true, can_transfer_manager:true, can_remove_member:true }
const row = (role: ProjectMemberRow['roles'][number], id: string): ProjectMemberRow => ({ membership_id:id, person_id:`p-${id}`, display_name:id, project_id:'p', roles:[role], affiliation:{ classification:'EXTERNAL', organisation_name:'Acme', effective_from:'2026-01-01', effective_to:null }, effective_from:'2026-09-01T00:00:00Z', effective_to:'2026-10-01T00:00:00Z', status:'ACTIVE' })
const renderPanel = (overrides: Partial<React.ComponentProps<typeof MembersPanel>> = {}) => render(<MembersPanel projectId="p" members={[row('PROJECT_OWNER','owner'),row('PROJECT_MEMBER','member'),row('PROJECT_AUDITOR','auditor')]} capabilities={caps} loading={false} error={null} onRetry={vi.fn()} searchCandidates={vi.fn().mockResolvedValue([{ person_id:'candidate', display_name:'Candidate', affiliation:{ classification:'INTERNAL', organisation_name:null } }])} {...overrides} />)
afterEach(() => { cleanup(); vi.restoreAllMocks() })
describe('VS002-08 Members', () => {
  it('groups and presents affiliation and bounded dates', () => { renderPanel(); expect(screen.getByText('Leadership')).toBeTruthy(); expect(screen.getByText('Delivery Team')).toBeTruthy(); expect(screen.getByText('Oversight')).toBeTruthy(); expect(screen.getAllByText(/EXTERNAL · Acme/).length).toBe(3); expect(screen.getAllByText(/9\/1\/2026/).length).toBe(3) })
  it('covers loading, empty, error and capability visibility', () => { const retry=vi.fn(); const { rerender }=renderPanel({ loading:true }); expect(screen.getByText('Loading members...')).toBeTruthy(); rerender(<MembersPanel projectId="p" members={[]} capabilities={null} loading={false} error="Denied" onRetry={retry} searchCandidates={vi.fn()} />); fireEvent.click(screen.getByText('Retry')); expect(retry).toHaveBeenCalled(); rerender(<MembersPanel projectId="p" members={[]} capabilities={{...caps,can_invite_member:false,can_change_ordinary_role:false,can_transfer_owner:false,can_transfer_manager:false,can_transfer_sponsor:false,can_remove_member:false}} loading={false} error={null} onRetry={retry} searchCandidates={vi.fn()} />); expect(screen.getByText('No current project members.')).toBeTruthy() })
  it('searches, selects and admits a stable Person with canonical fields', async () => { const search=vi.fn().mockResolvedValue([{ person_id:'candidate',display_name:'Candidate',affiliation:null }]); vi.mocked(apiFetch).mockResolvedValue({} as never); renderPanel({ searchCandidates:search }); await userEvent.click(screen.getByText('Add member')); const input=screen.getByLabelText('Find Person'); await userEvent.type(input,'C'); await userEvent.type(input,'a'); await waitFor(()=>expect(search).toHaveBeenCalledWith('Ca')); await userEvent.click(screen.getByText(/Candidate/)); await userEvent.click(screen.getByText('Confirm admission')); await waitFor(()=>expect(vi.mocked(apiFetch)).toHaveBeenCalledWith('/api/v1/projects/p/members',expect.objectContaining({method:'POST',body:expect.stringContaining('"person_id":"candidate"')}))) })
  it('keeps protected transfer separate and submits only allowed fields', async () => { vi.mocked(apiFetch).mockResolvedValue({} as never); renderPanel(); await userEvent.click(screen.getByText('Transfer')); const reason=screen.getByPlaceholderText('Required reason'); await userEvent.type(reason,'handover'); vi.spyOn(window,'confirm').mockReturnValue(true); await userEvent.click(screen.getByText('Confirm transfer')); await waitFor(()=>expect(vi.mocked(apiFetch)).toHaveBeenCalledWith('/api/v1/projects/p/role-transfers',expect.objectContaining({method:'POST',body:expect.not.stringMatching(/actor|correlation|outgoing|effective_at|operation/)}))) })
  it('ordinary editor limits roles and submits only role/reason then refreshes', async () => { const retry=vi.fn(); vi.mocked(apiFetch).mockResolvedValue({} as never); renderPanel({ onRetry: retry }); await userEvent.click(screen.getAllByText('Manage')[0]); const select=screen.getByRole('combobox'); expect(select.querySelectorAll('option')).toHaveLength(3); expect(screen.queryByRole('option',{name:'SPONSOR'})).toBeNull(); await userEvent.selectOptions(select,'PROJECT_OBSERVER'); await userEvent.type(screen.getByPlaceholderText('Optional reason'),'change'); await userEvent.click(screen.getByText('Save role')); await waitFor(()=>expect(vi.mocked(apiFetch)).toHaveBeenCalledWith('/api/v1/projects/p/members/member',{method:'PATCH',body:'{"role":"PROJECT_OBSERVER","reason":"change"}'})); expect(retry).toHaveBeenCalled() })
  it('surfaces backend authorization and transfer-required errors without fallback mutation', async () => { vi.mocked(apiFetch).mockRejectedValue(new ApiError(409,'Protected role','PROJECT_ROLE_TRANSFER_REQUIRED')); renderPanel(); await userEvent.click(screen.getAllByText('Manage')[0]); await userEvent.click(screen.getByText('Save role')); await waitFor(()=>expect(screen.getByText(/PROJECT_ROLE_TRANSFER_REQUIRED/)).toBeTruthy()); expect(vi.mocked(apiFetch)).toHaveBeenCalledTimes(1) })
  it('requires transfer reason and explicit confirmation, then refreshes with narrow payload', async () => { const retry=vi.fn(); vi.mocked(apiFetch).mockResolvedValue({} as never); const confirm=vi.spyOn(window,'confirm').mockReturnValue(false); renderPanel({ onRetry:retry }); await userEvent.click(screen.getByText('Transfer')); const submit=screen.getByText('Confirm transfer'); expect((submit as HTMLButtonElement).disabled).toBe(true); await userEvent.type(screen.getByPlaceholderText('Required reason'),'handover'); await userEvent.click(submit); expect(confirm).toHaveBeenCalled(); expect(apiFetch).not.toHaveBeenCalled(); confirm.mockReturnValue(true); await userEvent.click(submit); await waitFor(()=>expect(retry).toHaveBeenCalled()); const body=JSON.parse(vi.mocked(apiFetch).mock.calls[0][1]?.body as string); expect(Object.keys(body).sort()).toEqual(['new_membership_id','reason','role']) })
  it('requires removal confirmation, refreshes on success, and displays conflicts', async () => { const retry=vi.fn(); vi.mocked(apiFetch).mockResolvedValue({} as never); renderPanel({ onRetry:retry }); await userEvent.click(screen.getAllByText('Remove')[0]); const confirm=vi.spyOn(window,'confirm').mockReturnValue(false); await userEvent.click(screen.getByText('Confirm removal')); expect(apiFetch).not.toHaveBeenCalled(); confirm.mockReturnValue(true); await userEvent.type(screen.getByPlaceholderText('Optional reason'),'cleanup'); await userEvent.click(screen.getByText('Confirm removal')); await waitFor(()=>expect(retry).toHaveBeenCalled()); vi.mocked(apiFetch).mockRejectedValue(new ApiError(409,'Blocked','ACTIVE_RESPONSIBILITIES_EXIST')); await userEvent.click(screen.getAllByText('Remove')[0]); confirm.mockReturnValue(true); await userEvent.click(screen.getByText('Confirm removal')); await waitFor(()=>expect(screen.getByText(/ACTIVE_RESPONSIBILITIES_EXIST/)).toBeTruthy()) })
  it('surfaces a submission-time PROJECT_ACCESS_DENIED without fallback mutation', async () => { vi.mocked(apiFetch).mockRejectedValue(new ApiError(403, 'Denied', 'PROJECT_ACCESS_DENIED')); renderPanel(); await userEvent.click(screen.getAllByText('Manage')[0]); await userEvent.click(screen.getByText('Save role')); await waitFor(() => expect(screen.getByText(/PROJECT_ACCESS_DENIED/)).toBeTruthy()); expect(vi.mocked(apiFetch)).toHaveBeenCalledTimes(1) })
  it('surfaces required-holder and removal conflicts without compensating mutation', async () => { for (const code of ['LAST_REQUIRED_ROLE_HOLDER', 'MEMBER_REMOVAL_NOT_PERMITTED']) { cleanup(); vi.clearAllMocks(); vi.mocked(apiFetch).mockRejectedValue(new ApiError(409, 'Blocked', code)); renderPanel(); vi.spyOn(window, 'confirm').mockReturnValue(true); await userEvent.click(screen.getAllByText('Remove')[0]); await userEvent.click(screen.getByText('Confirm removal')); await waitFor(() => expect(screen.getByText(new RegExp(code))).toBeTruthy()); expect(vi.mocked(apiFetch)).toHaveBeenCalledTimes(1) } })
  it('prevents a second submission while a representative mutation is pending', async () => { let resolve: () => void = () => undefined; vi.mocked(apiFetch).mockImplementation(() => new Promise<void>((r) => { resolve = r })); renderPanel(); await userEvent.click(screen.getAllByText('Manage')[0]); const save = screen.getByText('Save role'); await userEvent.click(save); await userEvent.click(save); expect(vi.mocked(apiFetch)).toHaveBeenCalledTimes(1); resolve(); await waitFor(() => expect(vi.mocked(apiFetch)).toHaveBeenCalledTimes(1)) })
})
