import { useState } from 'react'
import { ApiError, apiFetch } from '../../lib/api'
import type { MembershipCapabilities, ProjectMemberRow } from '../../types/members'
import type { MemberCandidate } from './useProjectMembers'

interface Props { projectId:string; members:ProjectMemberRow[]; capabilities:MembershipCapabilities|null; loading:boolean; error:string|null; onRetry:()=>void; searchCandidates:(query:string)=>Promise<MemberCandidate[]> }
const groups = [{ title:'Leadership', roles:['PROJECT_SPONSOR','PROJECT_OWNER','PROJECT_MANAGER'] }, { title:'Delivery Team', roles:['PROJECT_MEMBER'] }, { title:'Oversight', roles:['PROJECT_OBSERVER','PROJECT_AUDITOR'] }] as const
const ordinary = ['PROJECT_MEMBER','PROJECT_OBSERVER','PROJECT_AUDITOR'] as const
const protectedRoles = ['PROJECT_SPONSOR','PROJECT_OWNER','PROJECT_MANAGER'] as const
const roleLabel = (r:string) => r.replace('PROJECT_','').replaceAll('_',' ')
const errorText = (e:unknown) => e instanceof ApiError ? `${e.code ?? 'REQUEST_FAILED'}: ${e.message}` : e instanceof Error ? e.message : 'Request failed.'
const canTransfer = (role:string, c:MembershipCapabilities) => role === 'PROJECT_SPONSOR' ? c.can_transfer_sponsor : role === 'PROJECT_OWNER' ? c.can_transfer_owner : c.can_transfer_manager

export function MembersPanel({ projectId, members, capabilities, loading, error, onRetry, searchCandidates }:Props) {
  const [addOpen,setAddOpen]=useState(false); const [query,setQuery]=useState(''); const [candidates,setCandidates]=useState<MemberCandidate[]>([]); const [selected,setSelected]=useState<MemberCandidate|null>(null); const [from,setFrom]=useState(new Date().toISOString().slice(0,10)); const [to,setTo]=useState(''); const [reason,setReason]=useState(''); const [editing,setEditing]=useState<ProjectMemberRow|null>(null); const [transfer,setTransfer]=useState<{role:typeof protectedRoles[number];member:ProjectMemberRow}|null>(null); const [remove,setRemove]=useState<ProjectMemberRow|null>(null); const [busy,setBusy]=useState<string|null>(null); const [actionError,setActionError]=useState<string|null>(null)
  const run = async (key:string, request:()=>Promise<unknown>) => { setBusy(key); setActionError(null); try { await request(); onRetry(); setAddOpen(false); setEditing(null); setTransfer(null); setRemove(null); setSelected(null); setCandidates([]); setQuery('') } catch(e) { setActionError(errorText(e)) } finally { setBusy(null) } }
  if (loading) return <section className="panel"><p>Loading members...</p></section>
  if (error) return <section className="panel"><div className="auth-error" role="alert">{error}</div><button className="secondary-button" type="button" onClick={onRetry}>Retry</button></section>
  return <section className="panel members-panel"><header className="panel-header"><div><h2>Members</h2><p className="muted">Current effective project membership</p></div>{capabilities?.can_invite_member && <button className="primary-button" type="button" onClick={()=>setAddOpen(!addOpen)}>Add member</button>}</header>{actionError&&<div className="auth-error" role="alert">{actionError}</div>}
    {addOpen&&<form className="member-form" onSubmit={e=>{e.preventDefault();if(!selected)return;void run('add',()=>apiFetch(`/api/v1/projects/${projectId}/members`,{method:'POST',body:JSON.stringify({person_id:selected.person_id,role:'PROJECT_MEMBER',effective_from:new Date(from).toISOString(),effective_to:to?new Date(to).toISOString():null})}))}}><label>Find Person<input value={query} onChange={e=>{const v=e.target.value;setQuery(v);setSelected(null);if(v.trim().length>=2)void searchCandidates(v).then(setCandidates).catch(c=>setActionError(errorText(c)))}} /></label>{candidates.map(c=><button className="secondary-button" type="button" key={c.person_id} onClick={()=>{setSelected(c);setCandidates([]);setQuery(c.display_name)}}>{c.display_name} · {c.affiliation?.classification??'Affiliation unavailable'}</button>)}<label>Effective from<input type="date" value={from} onChange={e=>setFrom(e.target.value)} required /></label><label>Effective to<input type="date" value={to} onChange={e=>setTo(e.target.value)} /></label><button className="primary-button" disabled={busy==='add'||!selected} type="submit">{busy==='add'?'Adding...':'Confirm admission'}</button></form>}
    {members.length===0?<p className="muted">No current project members.</p>:groups.map(g=>{const ms=members.filter(m=>m.roles.some(r=>g.roles.includes(r as never)));return <div className="member-group" key={g.title}><h3>{g.title}</h3>{ms.length===0?<p className="muted">None</p>:ms.map(m=><article className="member-card" key={m.membership_id}><div><strong>{m.display_name}</strong><div className="muted">{m.roles.map(roleLabel).join(', ')}</div><small>{m.affiliation?.classification??'Affiliation unavailable'}{m.affiliation?.organisation_name?` · ${m.affiliation.organisation_name}`:''}</small></div><div className="member-meta"><span>{m.status} · {new Date(m.effective_from).toLocaleDateString()} – {m.effective_to?new Date(m.effective_to).toLocaleDateString():'Open-ended'}</span>{capabilities?.can_change_ordinary_role&&m.roles.some(r=>ordinary.includes(r as never))&&<button className="secondary-button" type="button" onClick={()=>{setEditing(m);setReason('')}}>Manage</button>}{capabilities&&m.roles.some(r=>protectedRoles.includes(r as never)&&canTransfer(r,capabilities))&&<button className="secondary-button" type="button" onClick={()=>setTransfer({role:m.roles.find(r=>protectedRoles.includes(r as never)) as typeof protectedRoles[number],member:m})}>Transfer</button>}{capabilities?.can_remove_member&&<button className="secondary-button" type="button" onClick={()=>setRemove(m)}>Remove</button>}</div></article>)}</div>})}
    {editing&&<form className="member-form" onSubmit={e=>{e.preventDefault();const role=(e.currentTarget.elements.namedItem('role') as HTMLSelectElement).value;void run('edit',()=>apiFetch(`/api/v1/projects/${projectId}/members/${editing.membership_id}`,{method:'PATCH',body:JSON.stringify({role,reason:reason||null})}))}}><h3>Manage {editing.display_name}</h3><select name="role" defaultValue={editing.roles.find(r=>ordinary.includes(r as never))??'PROJECT_MEMBER'}>{ordinary.map(r=><option key={r} value={r}>{roleLabel(r)}</option>)}</select><input placeholder="Optional reason" value={reason} onChange={e=>setReason(e.target.value)} /><button className="primary-button" disabled={busy==='edit'} type="submit">Save role</button></form>}
    {transfer&&<form className="member-form" onSubmit={e=>{e.preventDefault();if(!reason.trim()||!window.confirm(`Confirm ${roleLabel(transfer.role)} appointment/transfer?`))return;void run('transfer',()=>apiFetch(`/api/v1/projects/${projectId}/role-transfers`,{method:'POST',body:JSON.stringify({role:transfer.role,new_membership_id:transfer.member.membership_id,reason:reason.trim()})}))}}><h3>{roleLabel(transfer.role)} appointment / transfer</h3><p>Incoming holder: {transfer.member.display_name}. The protected responsibility will move or be appointed.</p><input placeholder="Required reason" value={reason} onChange={e=>setReason(e.target.value)} required /><button className="primary-button" disabled={busy==='transfer'||!reason.trim()} type="submit">Confirm transfer</button></form>}
    {remove&&<form className="member-form" onSubmit={e=>{e.preventDefault();if(!window.confirm(`Remove ${remove.display_name}?`))return;void run('remove',()=>apiFetch(`/api/v1/projects/${projectId}/members/${remove.membership_id}`,{method:'DELETE',body:JSON.stringify({reason:reason||null})}))}}><h3>Remove {remove.display_name}</h3><p>Current roles: {remove.roles.map(roleLabel).join(', ')}</p><input placeholder="Optional reason" value={reason} onChange={e=>setReason(e.target.value)} /><button className="primary-button" disabled={busy==='remove'} type="submit">Confirm removal</button></form>}
  </section>
}
